[package]
name = "transitfeed"
description = "GTFS public transit decoder/encoder and utilities"
license = "MIT"
repository = "https://github.com/bfrog/transitfeed"
version = "0.1.4"
authors = ["Tom Burdick <thomas.burdick@gmail.com>"]
keywords = ["transit", "gtfs", "transitfeed"]

[dependencies]
quick-csv = "0.1"
zip = "0.1"

[dependencies.chrono]
version = "0.2"

[lib]
bench=false
