[package]
name = "transitfeed"
description = "Public transit decoder/encoder and utilities"
license = "MIT"
repository = "https://github.com/bfrog/transit"
version = "0.1.0"
authors = ["Tom Burdick <thomas.burdick@gmail.com>"]
keywords = ["transit", "gtfs", "transitfeed"]

[dependencies]
error-chain = "0.1"
zip = "0.1"
quick-csv = "0.1"

[dependencies.chrono]
version = "0.2"
